image: node:9.4.0

image: node:9.4.0

pages:
  script:
    - yarn install
    - yarn lerna run --scope react-frontend-developer build --parallel
    - mv workspaces/homepage/public public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules/
  only:
    - master
