ID = "942f26ac-6a26-41c6-95e8-898da174f3b7"

[build]
  # This is the directory to change to before starting a build.
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  base    = "."
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "workspaces/homepage/public/"
  # This will be your default build command
  command = "yarn deploy"

[build.environment]
  YARN_VERSION = "1.10.1"
